# Generated by Django 4.1.2 on 2022-10-31 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.modules'),
        ),
    ]
