# Generated by Django 4.1 on 2022-12-14 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_alter_quiz_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=2555)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('identification_questions', models.ManyToManyField(to='quiz.identification')),
                ('mcq_questions', models.ManyToManyField(to='quiz.mcq')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.modules')),
                ('tof_questions', models.ManyToManyField(to='quiz.trueorfalse')),
            ],
        ),
        migrations.DeleteModel(
            name='quiz',
        ),
    ]
