# Generated by Django 4.1 on 2022-12-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_quizzes_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='creator',
        ),
    ]
