# Generated by Django 4.1 on 2022-12-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0012_remove_quizzes_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='identification_questions',
            field=models.ManyToManyField(blank=True, to='quiz.identification'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='mcq_questions',
            field=models.ManyToManyField(blank=True, to='quiz.mcq'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='tof_questions',
            field=models.ManyToManyField(blank=True, to='quiz.trueorfalse'),
        ),
        migrations.CreateModel(
            name='scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('total_items', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
